version: "2"

services:
  blog:
    container_name: chall-blog-webapp
    build:
      context: ./blog
    restart: unless-stopped
    expose: 
      - 3333
    ports:
      - 3333:3333
  
  myprofile:
    container_name: chall-myprofile-webapp
    build:
      context: ./myprofile
    restart: unless-stopped
    expose: 
      - 3333

  nginx:
    container_name: chall-nginx
    build:
      context: ./nginx
    restart: unless-stopped
    ports: 
      - 80:80
    depends_on:
      - blog
      - myprofile
    #./nginx/nginx-conf:/etc/nginx/conf.d